### ISSUE TITLE
Seems like we're working on similar problems :)

### ISSUE THREAD

**Issue by machty** [jwlawrence/ember-tri-state#1]
Cool addon :)

It seems like we're both trying to expand upon ember-concurrency and build some conventions around handling all the various async states surrounding a piece of data, which is still a pretty unsolved problem in Ember that doesn't have any conventions surrounding it.

Not sure if you're the Ember community Slack but if so it'd be cool to bounce some ideas around; the EC channel is `#e-concurrency`

In the meantime here are some experimental Twiddles i've been working on that have some similar primitives as this addon's. 

https://ember-twiddle.com/8d8a82ca30906888e8dd7a2436c7abdd
https://ember-twiddle.com/f7a2c3b60502420a9e48a8c0edd9b279?fileTreeShown=false&numColumns=2&openFiles=helpers.state-for.js%2Ctemplates.application.hbs

**Comment by jwlawrence** [comment]
Hey @machty thanks for taking a look and for sharing the twiddles. It's interesting seeing how we've taken different approaches to solving basically the same problem. I'm already starting to get some new ideas from what you've shared, so I'd definitely be interested to hear your more of your thoughts.

I'll reach out to you on Slack and we can talk more. Thanks!

**Comment by jwlawrence** [comment]
I ended up pulling e-c out from this component since I ran into some issues with the original approach. The main problem was the need to execute actions from external sources (sibling components, route model hooks, etc) without relying on events. This became difficult because tri-state expected a function that returned a promise, rather than the promise itself, which was then e-c "taskified" internally. Actions to interact with the task instance were scoped to tri-state which made it difficult to interact with the data from parents and siblings.

In an attempt to stay true to DDAU and reduce complexity I decided to leverage the promiseProxyMixin to derive the state of promises. Now it can accept raw promises, objects and arrays of promises, and of course ember-concurrency task instances. So now the user has more control over the e-c task itself and this component only worries about basic state and component rendering.

I'm still very interested in finding new ways to implement e-c, so I'll I'm sure we'll chat in the future. Thanks!
