### ISSUE TITLE
Interactions with Fastboot

### ISSUE THREAD

**Issue by nickiaconis** [jwlawrence/ember-tri-state#11]
> A note on SEO: Since we bypass the model hook in the route, fastboot will render the page immediately without any data. If you are relying on fastboot for SEO you will probably want to continue resolving data in your model hook and using tri-state only for non-SEO imperative content (like loading tweets or comments for example)

I've been thinking about this note from the README regarding SEO/fastboot in light of https://github.com/jwlawrence/ember-tri-state/commit/873d74776743e31ec7321da7c8575d6347f7233b, which allows non-Promise primitives to be passed to `tri-state`. I think it should be possible to build a small helper that essentially escapes `tri-state` during SSR, but retains the benefits client-side.

Something like:
```javascript
export default function ssrHelper(hashOfPromises) {
  if (isSSR) { // <-- TODO: how to determine this?
    return Ember.RSVP.hash(hashOfPromises);
  }
  
  return hashOfPromises;
}
```

Which could be used like:
```javascript
import ssrHelper from 'ember-tri-state/helpers/ssr';

export default Ember.Route.extend({
  model(params) {
    const promises = {
      // make some requests here
    };

    return ssrHelper(promises);
  },
});
```

Do you think such a helper is feasible and worthwhile? Would it solve the SSR incompatibility `tri-state` faces to an acceptable degree? Would you envision it as something that falls under the umbrella of `ember-tri-state`?

**Comment by jwlawrence** [comment]
Good idea @nickiaconis. It turns out that fastboot apps do have a means of solving this problem as outlined here: https://ember-fastboot.com/docs/user-guide#use-model-hooks-to-defer-rendering

It might look something like this:
```
import Route from 'ember-route';

export default Route.extend({
  fastboot: inject.service(),

  model() {
    return {
      postsRequest: this.store.findAll('post'),
    };
  },

  afterModel() {
    if (this.get('fastboot.isFastBoot')) {
      return this.store.findAll('post');
    }  
  }
});
```

Of course, that only addresses the issue for fastboot apps, since the service is able to tell you whether or not the app is being rendered server side. If you can pass a flag to determine if your app is running in SSR mode, this approach should work though regardless.

Your `ssrHelper` does clean things up a bit and removes the need to add the `afterModel` hook, but I'm not sure it should live within the scope of ember-tri-state. Unless there is a reliable way to determine that an app is running in SSR mode, fastboot or otherwise, I think it should be left to the individual app to implement the helper.

I'm open to discussion though, so let me know if you agree or disagree. Thanks!
